### PR TITLE
ci: correct the appraised versions of redis

### PR DESCRIPTION
**Pull request by robbkidd**
Correcting some copy-pasta. Not adding 5.x because of deprecations yet to be addressed.

### CODE REVIEW

**Review by arielvalentin — COMMENTED** [review]
Are all of these minor versions receiving maintainer updates?

**Comment by robbkidd** [comment]
If this goes like it did in my dev environment, we'll see deprecations on `redis.queue` used in the test suite starting with v4.6.

**Comment by robbkidd** [comment]
> Are all of these minor versions receiving maintainer updates?

I doubt it. I don't think there are maintained minor branches. I did the range as a first commit to so we could all see where things get weird if they get weird. For v4, I bet we can just ride with the ~> 4.x and dial the change in this PR down to just that prior to merge.

Adding v5 failed the test suite. I didn't pick that work up yet.

**Comment by robbkidd** [comment]
You know what would make [this CI output](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/5558967974/jobs/10154611321?pr=565#step:4:70) nicer to look at? [Rollups and emoji](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/559). 😀

**Pull request closed without merging**
