### PR TITLE
Add support for X-Ray remote sampling

### PR DESCRIPTION
**Pull request by gillesbergerp**
This implements https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/714

### CODE REVIEW

**Review by arielvalentin — COMMENTED** [review]
This may sound naive but, why is this not using the AWS XRay SDK to interact with the API?

**Comment by gillesbergerp** [comment]
Not at all and I am happy to adapt it but I was following the Java counterpart in this regard (https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/aws-xray). This also makes it easy to leave authentication tothe awsproxy extension for the collector as opposed to the application.

**Comment by arielvalentin** [comment]
Oh I see. So this does not make requests to the AWS API but rather to a collector to get remote sampling rates?

**Comment by gillesbergerp** [comment]
The [awsproxy](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/awsproxy) is an extension for the OpenTelemetry collector "accepts requests without any authentication of AWS signatures applied and forwards them to the AWS API, applying authentication and signing" and is developed by AWS in-house.

**Comment by arielvalentin** [comment]
> The [awsproxy](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/awsproxy) is an extension for the OpenTelemetry collector "accepts requests without any authentication of AWS signatures applied and forwards them to the AWS API, applying authentication and signing" and is developed by AWS in-house. So the sampling rates/targets are still obtained from the X-Ray API - there just sits a proxy in-between.

Understood. So this implementation would only work if the Collector were a proxy since it would be handling signing requests.

E.g. 

```mermaid
sequenceDiagram
    OTel SDK X-Ray Remote Sampler ->>otel-col-aws-proxy: "/SamplingTargets" 
    otel-col-aws-proxy->>otel-col-aws-proxy: Generate Signed Request
    otel-col-aws-proxy->>AWS XRay API: "/SamplingTargets"
    AWS XRay API-->>otel-col-aws-proxy: SamplingTargetsResponse
    otel-col-aws-proxy-->> OTel SDK X-Ray Remote Sampler: SamplingTargetsResponse
```

Is that right?

**Comment by gillesbergerp** [comment]
Yes, that's right. Unfortunately, the official X-Ray client does not accept unsigned requests (`Aws::Errors::MissingCredentialsError: unable to sign request without credentials set`)

**Comment by arielvalentin** [comment]
Thank you for taking the time to patiently explain this to me.

With that in mind, I'll take a look at this PR later this week.

**Comment by gillesbergerp** [comment]
Thank you very much. Please let me know if I can be of assistance

**Pull request closed without merging**
