### PR TITLE
feat: Use Rack Middleware Helper

### PR DESCRIPTION
**Pull request by arielvalentin**
The Rack instrumentation supports the ability to use the Rack::Events API for instrumentation.

This change makes updates instrumentations that depend on the Rack instrumentation to use the Events based instrumentation.

### CODE REVIEW

**Review by mwear — APPROVED** [review]
LGTM

**Review by robbkidd — APPROVED** [review]
It works!

**Review by dazuma — CHANGES_REQUESTED** [review]
As discussed in the SIG meeting, consider `feat:` as the conventional commit tag.

**Comment by robbkidd** [comment]
Updated the convcommit preamble. With this change, a user can twiddle the Rack instrumentation config to use the Rack Events-based instrumentation, so new capabilities!

**Review by dazuma — APPROVED** [review]
👍🏼

**Comment by arielvalentin** [comment]
@dazuma once this is merged would you mind releasing a new version of the gems that were impacted by this change? I believe that would be:

- `actionpack`
- `sinatra`
- `rails`
- `all`

**Pull request merged**
