### PR TITLE
ci: Add nightly builds

### PR DESCRIPTION
**Pull request by arielvalentin**
This should allow us to get ahead of any gem incompatabilities

### CODE REVIEW

**Comment by arielvalentin** [comment]
@kaylareopelle I deleted the canary workflows in this PR: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/947

**Comment by kaylareopelle** [comment]
> @kaylareopelle I deleted the canary workflows in this PR: #947

@arielvalentin Thanks, I missed that PR! What about this workflow? https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/.github/workflows/ci-contrib-canary.yml

**Comment by arielvalentin** [comment]
UGG I missed that one huh

**Comment by kaylareopelle** [comment]
All good! Thanks for taking it out!

**Pull request merged**
