### PR TITLE
feat: render layout for action view

### LINKED ISSUE #407: Action view instrumentation missing render layout
Thanks for this great gem!! And excellent work!!

**Description of the bug**

Hello, i have noticed that my app is not generating action view render layout traces. I checked the source code and there isn`t a subscription for that event:
https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/07a8a9b375dbfbe4f2194e1516d968bb7a7a53db/instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/railtie.rb#L9-L14

This is intend? If not i can create this PR.

Rails subscription event:
https://guides.rubyonrails.org/active_support_instrumentation.html#render-layout-action-view

### PR DESCRIPTION
**Pull request by PedroAugustoRamalhoDuarte**
- Add render_layout.action_view for action view instrumentation
- Setup a the demonstration for generates traces for layout.

Example for tracing in demonstration
```
#<struct OpenTelemetry::SDK::Trace::SpanData
 name="action_view render_template",
 kind=:internal,
 status=#<OpenTelemetry::Trace::Status:0x00007efe631dc460 @code=1, @description="">,
 parent_span_id="\xE3\xA9\xE5\x8F\xC3Q\r\xEA",
 total_recorded_attributes=2,
 total_recorded_events=0,
 total_recorded_links=0,
 start_timestamp=1683842171697345069,
 end_timestamp=1683842171697418853,
 attributes={"identifier"=>"/home/pedro/IdeaProjects/OpenSource/opentelemetry-ruby-contrib/instrumentation/action_view/example/views/test/index.html.erb", "layout"=>"layouts/application"},
 links=nil,
 events=nil,
 resource=
  #<OpenTelemetry::SDK::Resources::Resource:0x00007efe9468c510
   @attributes=
    {"service.name"=>"unknown_service",
     "process.pid"=>52980,
     "process.command"=>"/home/pedro/.asdf/installs/ruby/3.1.0/bin/rackup",
     "process.runtime.name"=>"ruby",
     "process.runtime.version"=>"3.1.0",
     "process.runtime.description"=>"ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]",
     "telemetry.sdk.name"=>"opentelemetry",
     "telemetry.sdk.language"=>"ruby",
     "telemetry.sdk.version"=>"1.2.0"}>,
 instrumentation_scope=#<struct OpenTelemetry::SDK::InstrumentationScope name="OpenTelemetry::Instrumentation::ActionView", version="0.5.0">,
 span_id="\x89J\xFD\\\xC5\xDD\x94\xBA",
 trace_id=")\xD6\x85\xDF2(\xB1\xA2)\xB4\xA1\#$=\x13\xB6",
 trace_flags=#<OpenTelemetry::Trace::TraceFlags:0x00007efe63c51648 @flags=1>,
 tracestate=#<OpenTelemetry::Trace::Tracestate:0x00007efe63c58c18 @hash={}>>
I, [2023-05-11T18:56:11.698782 #52980]  INFO -- :   Rendered views/test/index.html.erb within layouts/application (Duration: 1.4ms | Allocations: 1058)
#<struct OpenTelemetry::SDK::Trace::SpanData
 name="action_view render_layout",
 kind=:internal,
 status=#<OpenTelemetry::Trace::Status:0x00007efe631dc460 @code=1, @description="">,
 parent_span_id="\x00\x00\x00\x00\x00\x00\x00\x00",
 total_recorded_attributes=1,
 total_recorded_events=0,
 total_recorded_links=0,
 start_timestamp=1683842171697281192,
 end_timestamp=1683842171698846487,
 attributes={"identifier"=>"/home/pedro/IdeaProjects/OpenSource/opentelemetry-ruby-contrib/instrumentation/action_view/example/views/layouts/application.html.erb"},
 links=nil,
 events=nil,
 resource=
  #<OpenTelemetry::SDK::Resources::Resource:0x00007efe9468c510
   @attributes=
    {"service.name"=>"unknown_service",
     "process.pid"=>52980,
     "process.command"=>"/home/pedro/.asdf/installs/ruby/3.1.0/bin/rackup",
     "process.runtime.name"=>"ruby",
     "process.runtime.version"=>"3.1.0",
     "process.runtime.description"=>"ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]",
     "telemetry.sdk.name"=>"opentelemetry",
     "telemetry.sdk.language"=>"ruby",
     "telemetry.sdk.version"=>"1.2.0"}>,
 instrumentation_scope=#<struct OpenTelemetry::SDK::InstrumentationScope name="OpenTelemetry::Instrumentation::ActionView", version="0.5.0">,
 span_id="\xE3\xA9\xE5\x8F\xC3Q\r\xEA",
 trace_id=")\xD6\x85\xDF2(\xB1\xA2)\xB4\xA1\#$=\x13\xB6",
 trace_flags=#<OpenTelemetry::Trace::TraceFlags:0x00007efe63c51648 @flags=1>,
 tracestate=#<OpenTelemetry::Trace::Tracestate:0x00007efe63c58c18 @hash={}>>
I, [2023-05-11T18:56:11.700144 #52980]  INFO -- :   Rendered layout views/layouts/application.html.erb (Duration: 2.8ms | Allocations: 2141)
I, [2023-05-11T18:56:11.700276 #52980]  INFO -- : Completed 200 OK in 3ms (Views: 3.1ms | Allocations: 2383)


```

fixes #407

### CODE REVIEW

**Comment by PedroAugustoRamalhoDuarte** [comment]
Yes you are right, maybe we need this option to all rails instrumentation

**Comment by arielvalentin** [comment]
@ericmustin I suspect that this will add a single span per HTTP request because AFAIK a template is only allowed a single layout.

I'm also thinking we should probably add a "generic" way to unsubscribe to specific AS notifications unless it's conceptually simpler to have configuration options per instrumentation.

**Comment by ericmustin** [comment]
@arielvalentin @PedroAugustoRamalhoDuarte fair enough. if it's a single additional span then i dont think a config option should be blocking, but yes agreed some generic way to un-subscribe to an ASN notification would be nice. Would it be possible to add a test for this? otherwise LGTM, nice work!

**Review by ericmustin — APPROVED** [review]
nvmd we don't have a test suite for this, should be addressed, but not the responsibility of this pr, which is a good addition to the instrumentation

**Pull request merged**
