### PR TITLE
Appraise sidekiq 7

### PR DESCRIPTION
**Pull request by Subramanya-Murugesan**

### CODE REVIEW

**Comment by arielvalentin** [comment]
@Subramanya-Murugesan thank you for your contribution! In order for us to accept this submission we require you sign the EasyCLA. Thank you!

**Comment by Subramanya-Murugesan** [comment]
Done @arielvalentin

**Comment by arielvalentin** [comment]
Thank you! Please take a look at the actions test suite.

Tests are failing against sidekiq 7 and it looks like due to incompatibility.

Would you be able to help us with a contribution to make the instrumentation work with this version?

**Comment by Subramanya-Murugesan** [comment]
@arielvalentin Sure, will check and update

**Comment by arielvalentin** [comment]
@Subramanya-Murugesan I have been out sick for a while so sorry it took so long to re-run the tests. 

I see it is still failing here: https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/5334256348/jobs/9852578270?pr=527

**Comment by stevenharman** [comment]
This will be closed by #546

**Pull request closed without merging**
