### PR TITLE
docs: link to rdkafka example

### PR DESCRIPTION
**Pull request by rsanheim**
Noticed that the link to the rdkafka example is broken. This fixes that.

### CODE REVIEW

**Comment by simi** [comment]
Thanks for the PR @rsanheim. Would you mind to sign CLA as well?

**Review by simi — APPROVED** [review]

**Review by simi — CHANGES_REQUESTED** [review]
Please can you also update commit message according to https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/CONTRIBUTING.md#use-conventional-commit-messages?

**Comment by rsanheim** [comment]
@simi Think that should fix it.

**Review by kaylareopelle — APPROVED** [review]
Thanks for your PR, @rsanheim!

**Comment by kaylareopelle** [comment]
> @simi Updated and force pushed - think that should fix it.

@simi, did you want to take another look?

**Review by simi — APPROVED** [review]

**Pull request merged**
