### PR TITLE
fix: Allow traces inside jobs while avoiding Redis noise

### PR DESCRIPTION
**Pull request by kevinnio**
Previously, I attempted to removed the patch for `Sidekiq::Processor#process_one` altogether in an attempt to allow for traces inside jobs without having `:trace_processor_process_one` enabled. Doing this brought up an issue with the Redis instrumentation, which produced a new trace everytime a Sidekiq worker polled for a job, creating a lot of low-value traces. Additionally, some people expressed concerns about removing the `:trace_processor_process_one` option.

This allows for traces inside jobs by default while keeping all other behaviors the same. The `:trace_processor_process_one` is still there and Redis won't produce noise when polling for jobs.

See #545 for more info.

#### With `propagation_style: :link`
after otel patch - inside job

#### With `propagation_style: :child`
after otel patch - inside job - child

### CODE REVIEW

**Comment by arielvalentin** [comment]
@open-telemetry/ruby-contrib-approvers  It looks like we have some unrelated CI builds failing due to issues with Actions. Do these errors look familiar to y'all?

@kevinnio Thank you again for your contribution. I really appreciate your flexibility here and your willingness to continue submitting PRs.

I would like to request that you add some automated test coverage for this change before merging this PR.

**Comment by plantfansam** [comment]
I believe the test failures will be addressed by https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/581/files, once it's merged into master.

**Comment by kevinnio** [comment]
Thanks, y'all. Now that specs are fixed I'll add some of my own to cover the new patch.

**Comment by kevinnio** [comment]
@arielvalentin Added some specs to test the new patch.

**Review by arielvalentin — APPROVED** [review]

**Review by plantfansam — APPROVED** [review]

**Comment by kevinnio** [comment]
Specs failed with a segmentation fault. Probably a re-run would fix them.

**Comment by arielvalentin** [comment]
curses! rdkafka 0.12 and your blasted segfaults!!!

**Pull request merged**
