### PR TITLE
chore: Add Ruby 3.2 builds

### PR DESCRIPTION
**Pull request by arielvalentin**
This PR adds additional builds for Ruby 3.2 always using the latest version of bundler available for all Ruby versions. 

Unfortunately the appraisal gem is not fully compatible with Ruby 3.2 so I have added a temporary bash script to our GitHub actions that runs the tests with the appraisal generated gemfiles. 

See https://github.com/thoughtbot/appraisal/issues/199

Note: Anything that requires older versions of `google-protobuf` will likely fail. 

```console
Because every version of x depends on opentelemetry-exporter-otlp
>= 0.21.2, < 1.A
and every version of opentelemetry-exporter-otlp depends on google-protobuf ~>
3.19,
  every version of x requires google-protobuf ~> 3.19.
And because every version of google-protobuf depends on Ruby >= 2.5, < 3.2.dev,
  every version of x requires Ruby >= 2.5, < 3.2.dev.
So, because rails_6.1.gemfile depends on x >= 0
  and current Ruby version is = 3.2.0,
  version solving has failed.
```

### CODE REVIEW

**Comment by arielvalentin** [comment]
Appraisal failure symptoms here:

https://github.com/thoughtbot/appraisal/issues/199

**Comment by arielvalentin** [comment]
@clarissalimab Would you be able to lend a hand with helping getting a PR merged to fix https://github.com/thoughtbot/appraisal/issues/199?

**Review by robertlaurin — APPROVED** [review]
One question, when you update GH actions in a PR does the CI reflect those changes on the PR or do they only take effect after it gets merged and then on subsequent CI runs?

**Comment by arielvalentin** [comment]
@robertlaurin GitHub actions runs the workflows defined in the PR. 

Here is an example of the CI Action Running against this branch:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/252/checks#step:3:71

**Review by mwear — APPROVED** [review]

**Pull request merged**
